import { Component, inject, OnInit, signal } from '@angular/core';
import { forkJoin } from 'rxjs';
import { AdminService } from '../../core/admin.service';
import { Pagina, Rol } from '../../core/api.models';
@Component({selector:'app-accesos',templateUrl:'./accesos.component.html',styleUrl:'./accesos.component.scss'})
export class AccesosComponent implements OnInit {
 private readonly api=inject(AdminService);readonly roles=signal<Rol[]>([]);readonly paginas=signal<Pagina[]>([]);readonly selectedRole=signal(0);readonly selected=signal<Set<number>>(new Set());readonly loading=signal(true);readonly saving=signal(false);readonly message=signal('');readonly error=signal('');
 ngOnInit():void{forkJoin({roles:this.api.roles(),paginas:this.api.paginas()}).subscribe({next:r=>{this.roles.set(r.roles.content.filter(x=>x.estado));this.paginas.set(r.paginas.content.filter(x=>x.estado));this.loading.set(false);if(this.roles().length){this.selectedRole.set(this.roles()[0].id);this.loadAccess();}},error:()=>{this.loading.set(false);this.error.set('No se pudieron cargar los catálogos.');}});}changeRole(value:string):void{this.selectedRole.set(Number(value));this.loadAccess();}loadAccess():void{if(!this.selectedRole())return;this.loading.set(true);this.api.accesos(this.selectedRole()).subscribe({next:r=>{this.selected.set(new Set(r.map(x=>x.id)));this.loading.set(false);},error:()=>{this.error.set('No se pudieron cargar los permisos del rol.');this.loading.set(false);}});}toggle(id:number,checked:boolean):void{const next=new Set(this.selected());checked?next.add(id):next.delete(id);this.selected.set(next);}save():void{this.saving.set(true);this.error.set('');this.api.asignarAccesos(this.selectedRole(),[...this.selected()]).subscribe({next:r=>{this.selected.set(new Set(r.map(x=>x.id)));this.saving.set(false);this.message.set('Permisos guardados. El usuario debe volver a iniciar sesión para actualizar su menú.');},error:e=>{this.saving.set(false);this.error.set(e.error?.message??'No se pudieron guardar los permisos.');}});}
}
