import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminService } from '../../core/admin.service';
import { Rol } from '../../core/api.models';
@Component({selector:'app-roles',imports:[ReactiveFormsModule],templateUrl:'./roles.component.html',styleUrl:'./roles.component.scss'})
export class RolesComponent implements OnInit {
 private readonly api=inject(AdminService);private readonly fb=inject(FormBuilder);readonly rows=signal<Rol[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly modal=signal(false);readonly editing=signal<Rol|null>(null);readonly message=signal('');readonly error=signal('');readonly query=signal('');readonly filtered=computed(()=>{const q=this.query().toLowerCase();return q?this.rows().filter(x=>`${x.nombre} ${x.descripcion}`.toLowerCase().includes(q)):this.rows();});readonly form=this.fb.nonNullable.group({nombre:['',[Validators.required,Validators.pattern(/^[A-Z][A-Z0-9_]{1,49}$/)]],descripcion:['',[Validators.maxLength(200)]]});
 ngOnInit():void{this.load();}load():void{this.loading.set(true);this.api.roles().subscribe({next:r=>{this.rows.set(r.content);this.loading.set(false);},error:()=>{this.error.set('No se pudieron cargar los roles.');this.loading.set(false);}});}open(x?:Rol):void{this.editing.set(x??null);this.error.set('');this.form.reset({nombre:x?.nombre??'',descripcion:x?.descripcion??''});this.modal.set(true);}save():void{if(this.form.invalid){this.form.markAllAsTouched();return;}this.saving.set(true);const v=this.form.getRawValue();const body={nombre:v.nombre.trim().toUpperCase(),descripcion:v.descripcion.trim()||null};const req=this.editing()?this.api.actualizarRol(this.editing()!.id,body):this.api.crearRol(body);req.subscribe({next:()=>{this.saving.set(false);this.modal.set(false);this.message.set('Rol guardado correctamente.');this.load();},error:e=>{this.saving.set(false);this.error.set(this.apiMessage(e));}});}toggle(x:Rol):void{if(!confirm(`¿Deseas ${x.estado?'desactivar':'activar'} el rol ${x.nombre}?`))return;this.api.estadoRol(x.id,!x.estado).subscribe({next:()=>{this.message.set('Estado actualizado.');this.load();},error:e=>this.error.set(this.apiMessage(e))});}private apiMessage(e:HttpErrorResponse):string{return e.error?.message??'No se pudo completar la operación.';}
}
