import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminService } from '../../core/admin.service';
import { Pagina } from '../../core/api.models';
@Component({selector:'app-paginas',imports:[ReactiveFormsModule],templateUrl:'./paginas.component.html',styleUrl:'./paginas.component.scss'})
export class PaginasComponent implements OnInit {
 private readonly api=inject(AdminService);private readonly fb=inject(FormBuilder);readonly rows=signal<Pagina[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly modal=signal(false);readonly editing=signal<Pagina|null>(null);readonly message=signal('');readonly error=signal('');readonly query=signal('');readonly filtered=computed(()=>{const q=this.query().toLowerCase();return q?this.rows().filter(x=>`${x.nombre} ${x.ruta}`.toLowerCase().includes(q)):this.rows();});readonly form=this.fb.nonNullable.group({nombre:['',[Validators.required,Validators.maxLength(100)]],ruta:['',[Validators.required,Validators.pattern(/^\/[a-z0-9/-]+$/)]],icono:['',[Validators.maxLength(100)]]});
 ngOnInit():void{this.load();}load():void{this.loading.set(true);this.api.paginas().subscribe({next:r=>{this.rows.set(r.content);this.loading.set(false);},error:()=>{this.error.set('No se pudieron cargar las páginas.');this.loading.set(false);}});}open(x?:Pagina):void{this.editing.set(x??null);this.error.set('');this.form.reset({nombre:x?.nombre??'',ruta:x?.ruta??'',icono:x?.icono??''});this.modal.set(true);}save():void{if(this.form.invalid){this.form.markAllAsTouched();return;}this.saving.set(true);const v=this.form.getRawValue();const body={nombre:v.nombre.trim(),ruta:v.ruta.trim().toLowerCase(),icono:v.icono.trim()||null};const req=this.editing()?this.api.actualizarPagina(this.editing()!.id,body):this.api.crearPagina(body);req.subscribe({next:()=>{this.saving.set(false);this.modal.set(false);this.message.set('Página guardada correctamente.');this.load();},error:e=>{this.saving.set(false);this.error.set(this.apiMessage(e));}});}toggle(x:Pagina):void{if(!confirm(`¿Deseas ${x.estado?'desactivar':'activar'} ${x.nombre}?`))return;this.api.estadoPagina(x.id,!x.estado).subscribe({next:()=>{this.message.set('Estado actualizado.');this.load();},error:e=>this.error.set(this.apiMessage(e))});}private apiMessage(e:HttpErrorResponse):string{return e.error?.message??'No se pudo completar la operación.';}
}
